### ISSUE TITLE
Command List Error

### ISSUE THREAD

**Issue by nanashi883** [DanielaGC/ChinoKafuu#232]
Just forked a while ago to make a PR and this happening even though I've done 0 changes to the code yet. Is it known?

![image](https://user-images.githubusercontent.com/82495941/125315028-5bb0bf00-e354-11eb-893e-fea4c6044208.png)

**Comment by nayvcake** [comment]
This is an error that happens in the separation of `\` in the registry. You are probably on windows and the search is different in this case

Linux: `/`
Windows: `\` or `\\`.

I'm submitting an implementation.

**Comment by nanashi883** [comment]
Strange, I've tried on Heroku (afaik they uses Linux distribution) and still had the error. Anyways, it's fixed now. Thanks
