### ISSUE TITLE
Falha na inicialização do bot caso deixa o shardmanager controlando as shards automáticamente, em vez de apenas definir um numero de shards.

### ISSUE THREAD

**Issue by yNeyKs** [DanielaGC/ChinoKafuu#26]
Falha na inicialização do bot caso deixa o shardmanager controlando as shards automáticamente, em vez de apenas definir um numero de shards.
![image](https://user-images.githubusercontent.com/41455280/89933568-9ad70d00-dbe5-11ea-9677-8ee334f96fe5.png)

**Comment by MysteryMS** [comment]
Você configurou corretamente o config.json?

**Comment by yNeyKs** [comment]
Sim, pois se defino o numero de shards, exemplo, 1,2, 3, ele funciona corretamente, agora se defino como ('auto') dá erro.

**Comment by MysteryMS** [comment]
Quando você coloca o `totalShards` para **auto**, o discord.js faz uma requisição lá pra API do Discord pra pegar o recomendado pro seu bot.
Assim que definir o `totalShards` para **auto**, também adicione uma opção chamada `token` e defina-o com o token do seu bot
`token: NDkwNjExNjM2ODM1NTgxOTUz...`
Mais infos [aqui](https://discord.js.org/#/docs/main/stable/class/ShardingManager).
