### ISSUE TITLE
Make a command that shows the distance from one location to another location

### ISSUE THREAD

**Issue by nneston** [DanielaGC/ChinoKafuu#28]
The command would look like this:
You execute the command with a place of departure (ex: Paris), and then you place a place of arrival (ex: Portugal), and the answer would be the distance between the two locations (ex: Paris, France - Lisbon, Portugal 1605, 5km)

**Comment by nneston** [comment]
A public API that can be used in this command is that of Google Cloud, the Distance Matrix Service. You can see it [here.](https://developers.google.com/maps/documentation/javascript/distancematrix)

**Comment by MysteryMS** [comment]
Unfortunately, all Google Cloud's APIs are paid and we can't pay for an API right now. If you have any other ways, let us know.
Thanks!

> Effective July 16, 2018, a new pay-as-you-go pricing plan went into effect for Maps, Routes, and Places. To learn more about the new pricing and usage limits for your use of the JavaScript Distance Matrix service, see Usage and Billing for the Distance Matrix API.

**Comment by nneston** [comment]
Seeing it! Thank you for attention. 👀
