### ISSUE TITLE
How to make the config json?

### ISSUE THREAD

**Issue by NickSneaky** [DanielaGC/ChinoKafuu#38]
Maybe some of you didnt saw that the bot dont has a config.json and you gotta create it

1. Go to 'config.json.example'
2. Right click on it
3. Select 'edit with [your editing app e.x notepad++]'
4. Enter the information there
5. Save 
6. Rename to 'config.json' (delete the .example)
7. Done

**Comment by MysteryMS** [comment]
Of course, we won't commit directly the `config.json` file, whihc has _sensitive_ information. That's why we created the `config.json.example`: a template for guiding users on what they should put into the file. 

Closing and locking.
